### ISSUE TITLE
Missing NuGet packages

### ISSUE THREAD

**Issue by takineko-tfs** [TheFlightSims/windowsserver-mgmttools#15]
**Describe the bug**
The repo is missing NuGet packages for applications. This affects the repo globally.

**To Reproduce**
NuGet are missing while building an application and affect all other application

**Expected behavior**
The build must be completed successfully, but it returned an error show that NuGet packages are missing

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 (22623.1235)
 - Visual Studio 17.4.5 Enterprise

**Comment by TheFlightSimsOfficial** [comment]
Issue will be fixed in the future. 
If you have, you can take your time to contribute this repo.

Any question, reply this message.
All thanks.
